name: Weather Push

on:
  schedule:
    - cron: '0 23 * * *'  # UTC时间23点（北京时间早上7点）
  workflow_dispatch:  # 支持手动触发
  
permissions:  # 添加权限设置
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Create Config File
        run: |
          echo '${{ secrets.CONFIG_JSON }}' > config.json
          
      - name: Run weather push
        run: |
          python test.py
